### ISSUE TITLE
[Npc] Syndicate Magus

### ISSUE THREAD

**Issue by talosbane00** [revui/Legion_7.3.5-Project-Info#102]
This NPC is inside the textures
[https://it.classic.wowhead.com/npc=2591/syndicate-magus](url)
![Syndicate Magus](https://user-images.githubusercontent.com/60328315/73437037-e746b380-434b-11ea-854a-5b4f715c288a.jpg)
![Syndicate Magus 2](https://user-images.githubusercontent.com/60328315/73437044-ea41a400-434b-11ea-920b-67fbf2073d5e.jpg)

**Comment by revui** [comment]
Fixed
