### ISSUE TITLE
[Quest] Wanted! Otto and Falconcrest

### ISSUE THREAD

**Issue by talosbane00** [revui/Legion_7.3.5-Project-Info#105]
Wrong Area Quest
[https://classic.wowhead.com/quest=685/wanted-otto-and-falconcrest](url)
![Wanted! Otto and Falconcrest](https://user-images.githubusercontent.com/60328315/73437378-84095100-434c-11ea-9344-1eaf12752ae4.jpg)

**Comment by revui** [comment]
Fixed
