### ISSUE TITLE
[Npc] Whiterbark Axe Thrower

### ISSUE THREAD

**Issue by talosbane00** [revui/Legion_7.3.5-Project-Info#106]
This NPC is in the ground and can attack me, I can't attack him
[https://it.classic.wowhead.com/npc=2554/witherbark-axe-thrower](url)
![Whiterbark Axe](https://user-images.githubusercontent.com/60328315/73437538-d5194500-434c-11ea-818c-22407cc680b1.jpg)
![Whiterbark Axe 2](https://user-images.githubusercontent.com/60328315/73437555-d8accc00-434c-11ea-869d-441ef479efd7.jpg)

**Comment by revui** [comment]
Fixed
