### ISSUE TITLE
[Quest] Worth Its Weight in Gold

### ISSUE THREAD

**Issue by talosbane00** [revui/Legion_7.3.5-Project-Info#107]
Wrong Area Quest
[https://it.classic.wowhead.com/quest=691/worth-its-weight-in-gold](url)
![Worth Its Weight in Gold](https://user-images.githubusercontent.com/60328315/73437672-1578c300-434d-11ea-887a-0a981cb9e45c.jpg)

**Comment by revui** [comment]
Fixed
