### ISSUE TITLE
[Quest] Diplomacy By Another Means

### ISSUE THREAD

**Issue by talosbane00** [revui/Legion_7.3.5-Project-Info#109]
There are too many Sabernout!
[https://www.wowhead.com/npc=37513/sabersnout](url)
[https://www.wowhead.com/quest=25044/diplomacy-by-another-means](url)
![Sabernout](https://user-images.githubusercontent.com/60328315/73461138-ee84b600-4379-11ea-9e4e-fc62b24f7aef.jpg)

**Comment by revui** [comment]
Fixed
