### ISSUE TITLE
[Quest] Shadra the Venom Queen

### ISSUE THREAD

**Issue by talosbane00** [revui/Legion_7.3.5-Project-Info#117]
There are 2 Shadra
[https://www.wowhead.com/quest=26419/shadra-the-venom-queen](url)
![Shandra the Venom Queen](https://user-images.githubusercontent.com/60328315/73469632-f5fe8c00-4386-11ea-8b00-635154c65939.jpg)

**Comment by revui** [comment]
Fixed
