### ISSUE TITLE
[Quest] Skulk Rock Clean-up

### ISSUE THREAD

**Issue by talosbane00** [revui/Legion_7.3.5-Project-Info#118]
Wrong Area Quest
[https://classic.wowhead.com/quest=2877/skulk-rock-clean-up](url)
![Skulk Rock Clean-Up](https://user-images.githubusercontent.com/60328315/73469884-542b6f00-4387-11ea-94f4-1300cb3a63d7.jpg)

**Comment by revui** [comment]
Fixed
