### ISSUE TITLE
[Quest] The Fargodeep Mine

### ISSUE THREAD

**Issue by talosbane00** [revui/Legion_7.3.5-Project-Info#12]
The quest marker after completing quest is in the wrong area on the minimap and on the map
![Fargodeep Mine 1](https://user-images.githubusercontent.com/60328315/73142988-23042380-4095-11ea-84c5-22f57c2d0720.jpg)
![Fargodeep Mine 2](https://user-images.githubusercontent.com/60328315/73142991-28616e00-4095-11ea-9e34-eb14c588bc46.jpg)

[https://classic.wowhead.com/quest=62/the-fargodeep-mine](url)

**Comment by revui** [comment]
Fixed. Will implemented with the next update.
