### ISSUE TITLE
[Npc] Skeletal Sorcerer

### ISSUE THREAD

**Issue by talosbane00** [revui/Legion_7.3.5-Project-Info#129]
This NPC can run inside the floor
[https://www.wowhead.com/npc=1784/skeletal-sorcerer](url)
![Skeletal Sorcerer](https://user-images.githubusercontent.com/60328315/73477511-b2128380-4394-11ea-83e3-4da8f9a98ea1.jpg)

**Comment by revui** [comment]
Fixed
