### ISSUE TITLE
[Quest] Gold Dust Exchange

### ISSUE THREAD

**Issue by talosbane00** [revui/Legion_7.3.5-Project-Info#13]
The quest marker after completing quest is in the wrong area on the map
![Gold Dust 1](https://user-images.githubusercontent.com/60328315/73143093-3b287280-4096-11ea-9bb2-e7e12f94810e.jpg)
[https://classic.wowhead.com/quest=47/gold-dust-exchange](url)

**Comment by revui** [comment]
Fixed. Will implemented with the next update.
