### ISSUE TITLE
[Quest] A new era for the Plaguelands

### ISSUE THREAD

**Issue by talosbane00** [revui/Legion_7.3.5-Project-Info#136]
Wrong Area Quest
[https://www.wowhead.com/quest=26999/a-new-era-for-the-plaguelands](url)
![A new era for the plaguelands](https://user-images.githubusercontent.com/60328315/73489005-2c013780-43aa-11ea-90c9-5b6f47fff1e8.jpg)

**Comment by revui** [comment]
Fixed
