### ISSUE TITLE
[Quest] Unusual Behavior... Even For Gnolls

### ISSUE THREAD

**Issue by talosbane00** [revui/Legion_7.3.5-Project-Info#137]
You can't complete quest even if you kill Modfang (I tried 2 times)
[https://www.wowhead.com/npc=45155/moldfang](url)
[https://www.wowhead.com/quest=27152/unusual-behavior-even-for-gnolls](url)
![Unusual Behavior  Even for Gnolls](https://user-images.githubusercontent.com/60328315/73489107-5f43c680-43aa-11ea-91e5-5e4234f70c95.jpg)
![Unusual Behavior  Even for Gnolls 2](https://user-images.githubusercontent.com/60328315/73489113-610d8a00-43aa-11ea-932b-0063d354c26a.jpg)

**Comment by revui** [comment]
Fixed
