### ISSUE TITLE
[NPC][Quest] A Pilot's revenge (26855)

### ISSUE THREAD

**Issue by Roodypoo0123** [revui/Legion_7.3.5-Project-Info#138]
[Mangeclaw](https://classic.wowhead.com/npc=1961/mangeclaw) is non-lootable hence blocking the completion of the quest he's related to.

![WoWScrnShot_013020_232729](https://user-images.githubusercontent.com/46425985/73496277-80abaf00-43b8-11ea-874e-c95f02e02151.jpg)

**Comment by revui** [comment]
Fixed
