### ISSUE TITLE
[Quest] The Jasperlode Mine

### ISSUE THREAD

**Issue by talosbane00** [revui/Legion_7.3.5-Project-Info#14]
The blue area of ​​the quest is huge and strange on the map
[https://classic.wowhead.com/quest=76/the-jasperlode-mine](url)
![Jasperlode Mine](https://user-images.githubusercontent.com/60328315/73143171-2bf5f480-4097-11ea-8f5e-7dba333d1eaf.jpg)

**Comment by Kyyteo** [comment]
quest_poi seems to be at fault. Will write a fix shortly

**Comment by revui** [comment]
Fixed. Will implemented with the next update.
