### ISSUE TITLE
[UI] Adventure Guide not working

### ISSUE THREAD

**Issue by Roodypoo0123** [revui/Legion_7.3.5-Project-Info#140]
It seems that the Adventure Guide is not working when trying to accept region quests. Clicking on the button has no effect.

![WoWScrnShot_013020_224610](https://user-images.githubusercontent.com/46425985/73496540-18a99880-43b9-11ea-857e-30ff8d50f32c.jpg)

**Comment by talosbane00** [comment]
Duplicate.
[https://github.com/revui/Legion_7.3.5-Project-Info/issues/98](url)

**Comment by Roodypoo0123** [comment]
Closing.
