### ISSUE TITLE
[Quest] Brother Against Brother

### ISSUE THREAD

**Issue by talosbane00** [revui/Legion_7.3.5-Project-Info#146]
There are just 3-4 Forsaken Trooper and I don't have any Provincial Minuteman that should helps me to complete quest.
[https://www.youtube.com/watch?v=_ucrVkktnxc](url)
[https://www.wowhead.com/quest=27202/brother-against-brother](url)
[https://www.wowhead.com/npc=45241/forsaken-trooper](url)

**Comment by revui** [comment]
Added missing Forsaken Troops.
Provincial Minuteman will added for aid soon.
