### ISSUE TITLE
[Quest] Saving the Young

### ISSUE THREAD

**Issue by Zube18** [revui/Legion_7.3.5-Project-Info#147]
The catching works with talking to the little hatchlings, but the whistle to aoe catch doesnt work.

https://www.wowhead.com/quest=24623/saving-the-young
https://www.youtube.com/watch?v=OwFT83QLJZw&feature=youtu.be&t=58 (aoe catching//whistle)

**Comment by Madliv21** [comment]
Can confirm, met Zube in the same area, had the same bug.
