### ISSUE TITLE
[Quest] Lost in the Floods

### ISSUE THREAD

**Issue by Selvi391** [revui/Legion_7.3.5-Project-Info#151]
When I press the quest item, doesn't work. Im on the top of the tower.
https://www.wowhead.com/quest=25187/lost-in-the-floods
![image](https://user-images.githubusercontent.com/60510795/73541897-3409b780-443c-11ea-9589-b5e511c0df7f.png)

**Comment by talosbane00** [comment]
Every tickets needs wowhead link :)
