### ISSUE TITLE
[Quest] Greasing the Wheel

### ISSUE THREAD

**Issue by talosbane00** [revui/Legion_7.3.5-Project-Info#154]
There are not any Banshee's Bells
[https://www.wowhead.com/quest=27369/greasing-the-wheel](url)
[https://www.wowhead.com/item=60984/banshees-bells](url)
![Greasing the Wheel](https://user-images.githubusercontent.com/60328315/73545877-83e87e80-443c-11ea-9db6-d9cecc509d6d.jpg)

**Comment by Roodypoo0123** [comment]
Confirmed.
![image](https://user-images.githubusercontent.com/46425985/73690690-36d10a80-46d1-11ea-98e5-e92acd3918f2.png)
