### ISSUE TITLE
[NPC] Too much interrupts 

### ISSUE THREAD

**Issue by Selvi391** [revui/Legion_7.3.5-Project-Info#156]
This npc spammed only interrupts, and it was really hard to kill. You can see in the video:
https://classic.wowhead.com/npc=3385/theramore-marine#abilities
https://www.youtube.com/watch?v=syt8t4JB0ZA&feature=youtu.be

**Comment by revui** [comment]
A wowhead link would be great about the npc

**Comment by Selvi391** [comment]
> A wowhead link would be great about the npc

Done.
