### ISSUE TITLE
[Allied Races] Mount missing on creation.

### ISSUE THREAD

**Issue by RealLushen** [revui/Legion_7.3.5-Project-Info#157]
Normally you get a Mount with creating a "Allied Race".
At Project-Legion/7.3.5 you don't :)

Best Regards,
Lushen

**Comment by revui** [comment]
Hello @RealLushen,
You was able to create an allied race character without the required achievements?

**Comment by RealLushen** [comment]
Yes I was able and it should stay like this, everyone hates the grind ^^
