### ISSUE TITLE
[Quest] Riverpaw Gnoll Bounty

### ISSUE THREAD

**Issue by talosbane00** [revui/Legion_7.3.5-Project-Info#16]
Wrong Quest indicator:
![Riverpaw Gnall Bounty](https://user-images.githubusercontent.com/60328315/73143247-22b95780-4098-11ea-96ae-dcfd7d29861d.png)
[https://classic.wowhead.com/quest=11/riverpaw-gnoll-bounty](url)

**Comment by revui** [comment]
Fixed. Will implemented with the next update.
