### ISSUE TITLE
[Quest] Zaeldarr the Outcast

### ISSUE THREAD

**Issue by talosbane00** [revui/Legion_7.3.5-Project-Info#160]
Double Zaeldarr.
[https://classic.wowhead.com/quest=6021/zaeldarr-the-outcast](url)
![Zaeldarr the Outcast](https://user-images.githubusercontent.com/60328315/73572529-4e11bd00-4471-11ea-89b4-43f56b2b091d.jpg)

**Comment by revui** [comment]
Fixed
