### ISSUE TITLE
[Quest] Hot On the Trail: Murlocs

### ISSUE THREAD

**Issue by talosbane00** [revui/Legion_7.3.5-Project-Info#17]
Wrong Quest Indicator:
![Hot on the trails Murlocs](https://user-images.githubusercontent.com/60328315/73143291-b854e700-4098-11ea-9b01-df90fe9429e0.jpg)
[https://www.wowhead.com/quest=26214/hot-on-the-trail-murlocs](url)

**Comment by revui** [comment]
Fixed. Will implemented with the next update.
