### ISSUE TITLE
(Quest) Crossroads Caravan Delivery

### ISSUE THREAD

**Issue by alymaster** [revui/Legion_7.3.5-Project-Info#174]
talking to Rocco Whipshank doesnt give you the option to summon the caravan to do the defending event to protect the caravan, therefore its unable to be completed

**Comment by revui** [comment]
Add a wowhead link with this quest. Thanks

**Comment by Maltien** [comment]
Here is link.

https://www.wowhead.com/quest=13975/crossroads-caravan-delivery
