### ISSUE TITLE
[Quest] Livin' the Life

### ISSUE THREAD

**Issue by talosbane00** [revui/Legion_7.3.5-Project-Info#18]
In this quest after using the quest item a player must spy a conversation between Glubtok [https://it.wowhead.com/npc=47162/glubtok](url) and the Shadowy Figure.
This conversation is missing but if you wait after some time the quest will be complete.
[https://www.wowhead.com/quest=26228/livin-the-life](url)
![Livin' the Life](https://user-images.githubusercontent.com/60328315/73143445-3ebdf880-409a-11ea-99cd-ca5d2bc55665.jpg)

**Comment by toolshmool** [comment]
That's what revui said earlier. Westfall works but the text is missing.

**Comment by talosbane00** [comment]
Oh didn't read that He said!

**Comment by toolshmool** [comment]
Why aren't you online on discord anymore?

**Comment by talosbane00** [comment]
My client crash everytime and I can't continue to play. So I must wait Revui and I hope that He can help me. I just finish to opent every tickets and I go to sleep :)
