### ISSUE TITLE
Quest: Be raptor (can not be accomplished)

### ISSUE THREAD

**Issue by Kexxi** [revui/Legion_7.3.5-Project-Info#189]
![unknown](https://user-images.githubusercontent.com/60041403/73594216-9205d000-450c-11ea-9241-768ca0b85a60.png)

https://www.youtube.com/watch?v=EY1TbBxxCKY

https://www.wowhead.com/quest=26775/be-raptor

**Comment by revui** [comment]
Wrong report.
Missing details, whats the issue with that quest. Please fill this report with proper informations

**Comment by Kexxi** [comment]
You pick up the quest from 'priestess Hu'rala' and you need to speak with him to "im ready for the mind control ritual priestess Hu'rala but this opportunity does not appear.
