### ISSUE TITLE
[Achievement] Represent

### ISSUE THREAD

**Issue by Beefkek** [revui/Legion_7.3.5-Project-Info#2]
Wrong trigger for the achievement. I got it after completing the quest Spare Parts.
Either https://www.wowhead.com/quest=9305/spare-parts or https://www.wowhead.com/quest=37445/spare-parts not sure what version of the quest I completed.
It could also have been triggered by the item reward, in this case, Beaten Plate Leggings https://www.wowhead.com/item=24423/beaten-plate-leggings

Proof: https://prnt.sc/qt6jx0

**Comment by Roodypoo0123** [comment]
Fashionista : Tabards (10 tabards) and Fashionista : Shirts suffers the same trigger problem.
