### ISSUE TITLE
[Quest] It's Alive!

### ISSUE THREAD

**Issue by talosbane00** [revui/Legion_7.3.5-Project-Info#20]
The Overloaded Harvest Golem moves very slowly and the two spells are not working properly. However, the quest can be completed but it takes too long.
[https://www.wowhead.com/quest=26257/its-alive](url)
[https://www.wowhead.com/npc=42601/overloaded-harvest-golem](url)

**Comment by revui** [comment]
Passive speed fixed, the ability 2 (rocket boots) need to use while targeted a Golem enemy.
Fixed. Will implemented with the next update.
