### ISSUE TITLE
[Quest] Feeding the Hungry and the Hopeless

### ISSUE THREAD

**Issue by talosbane00** [revui/Legion_7.3.5-Project-Info#21]
Food doesn't work with all the hungry. The player must continuously use the quest item with all the hungry and a lot of time is wasted.
![Feeding the Hungry and the Hopeless](https://user-images.githubusercontent.com/60328315/73143641-e3d9d080-409c-11ea-9e41-3fb2219c649f.jpg)
[https://www.wowhead.com/quest=26271/feeding-the-hungry-and-the-hopeless](url)

**Comment by revui** [comment]
Every Citizen around Sentinel Hill has been fixed, but please note: They NOT ALWAYS hungry. When a food icon appears under their head, they want your help! Creatures will respawn after 3 mins of feed.

Fixed. Will implemented with the next update.
