### ISSUE TITLE
They Should Fight

### ISSUE THREAD

**Issue by Kexxi** [revui/Legion_7.3.5-Project-Info#213]
This things make the feeling in me  THIS SERVER IS HARDLY BUGGED 👎  but its not can you fix this 😢  if you fix it it makes more LIFE in the game 😭 

![unknown](https://user-images.githubusercontent.com/60041403/73596491-b7053d80-4522-11ea-9a1c-5573872e97cc.png)

**Comment by talosbane00** [comment]
Remember to write wowhead link everytime for quests or for npcs.
If you want a nice/perfect server you should help us opening tickets with a bit patience. I know that is frustrating but if you have patience Revui can fix everything ^^
Trust me, He can fix 99% issues (maybe 100% xD)

**Comment by revui** [comment]
Fixed
