### ISSUE TITLE
Some bug idk what the title should be 

### ISSUE THREAD

**Issue by Kexxi** [revui/Legion_7.3.5-Project-Info#214]
They are waiting for the WC and they are agressive
![unknown](https://user-images.githubusercontent.com/60041403/73596543-1c592e80-4523-11ea-9679-f59525378e16.png)
Everywhere over the Ship the gnomes attacks me while they are sleeping on the ground 

Pointless Spider
![unknown](https://user-images.githubusercontent.com/60041403/73596538-0fd4d600-4523-11ea-94e9-3ca90e5ca8e9.png)

**Comment by talosbane00** [comment]
[Npc] And if an area have more than one NPC that is bugged write in title "Continent / Zone / Area" and write wowhead link for every npcs/mpb bugged with a shortly issue description and with some screenshot :)

**Comment by Kexxi** [comment]
Posted wrong picture :D
