### ISSUE TITLE
Instant death

### ISSUE THREAD

**Issue by Sedowr** [revui/Legion_7.3.5-Project-Info#217]
The Boulderfist Maulers in Stormgrade Keep will cause you to die instantly. It's not caused by the damage they do. In fact they do normal damage (got hit the first time i gone there, the second time i didn't get hit since i stunned the mob) 
https://classic.wowhead.com/npc=2569/boulderfist-mauler
![image](https://user-images.githubusercontent.com/60552532/73597328-7235d280-4533-11ea-8337-7d4c7e335069.png)
![image](https://user-images.githubusercontent.com/60552532/73597337-8e397400-4533-11ea-9758-7f31d003605c.png)

**Comment by Roodypoo0123** [comment]
Confirmed, no damage showing up in the log either.
