### ISSUE TITLE
[Npc] Stormwind City Guard (funny movement bug)

### ISSUE THREAD

**Issue by talosbane00** [revui/Legion_7.3.5-Project-Info#22]
Some Stormwind city guards sit immediately on the ground if they stop. If they start walking again they immediately get up.
![Stormwind City Guard 1](https://user-images.githubusercontent.com/60328315/73143764-48e1f600-409e-11ea-9e2f-0c3f46fbcc46.jpg)
![Stormwind City Guard 2](https://user-images.githubusercontent.com/60328315/73143766-4bdce680-409e-11ea-87d9-231c1cefcc36.jpg)
[https://it.classic.wowhead.com/npc=68/stormwind-city-guard](url)

**Comment by revui** [comment]
Fixed. Will implemented with the next update.
