### ISSUE TITLE
NPC waypoint/movement MEGATHREAD

### ISSUE THREAD

**Issue by revui** [revui/Legion_7.3.5-Project-Info#251]
Megathread for all npcs whom dont have proper movement, or just standing idle.

**Comment by Zube18** [comment]
https://www.wowhead.com/npc=35245/greystone-basilisk
Movement when attack. Otherwise no movement at all.

**Comment by Zube18** [comment]
https://www.wowhead.com/npc=35096/weakened-mosshoof-stag
No movement. When attacked just wiggle around on one spot sometimes or beeing rooted

**Comment by Zube18** [comment]
https://www.wowhead.com/quest=14129/runaway-shredder
Movement when attack. Otherwise no movement at all.

**Comment by Zube18** [comment]
https://www.wowhead.com/quest=36230/the-restless-spirit
Movement when attack. Otherwise no movement at all.

**Comment by talosbane00** [comment]
[https://www.wowhead.com/npc=46773/explorers-league-excavator](url)
53.86, 39.4
They don't dig and don't move

**Comment by Zube18** [comment]
https://www.wowhead.com/npc=8764/mistwing-ravager
https://www.wowhead.com/npc=6375/thunderhead-hippogryph

Movement when attack. Otherwise no movement at all.

**Comment by talosbane00** [comment]
[https://www.wowhead.com/npc=34366/warsong-vanguard](url)
[https://classic.wowhead.com/npc=4054/laughing-sister](url)
Movement when attack. Otherwise no movement at all.

**Comment by talosbane00** [comment]
Sometimes Irontree Stomper walks underground.
[https://classic.wowhead.com/npc=7139/irontree-stomper](url)
![Irontree Stomper](https://user-images.githubusercontent.com/60328315/73648938-f2b51a00-467e-11ea-88d7-6836e271924c.jpg)
![Irontree Stomper 2](https://user-images.githubusercontent.com/60328315/73648942-f47edd80-467e-11ea-9d2b-e05de70e160c.jpg)

**Comment by talosbane00** [comment]
Flying Toad.
[https://classic.wowhead.com/npc=1420/toad](url)
![Toad](https://user-images.githubusercontent.com/60328315/73648994-18422380-467f-11ea-94ea-9b4da49d73e8.jpg)
![Toad 2](https://user-images.githubusercontent.com/60328315/73649002-1aa47d80-467f-11ea-8b69-07cd68ebce68.jpg)

**Comment by Roodypoo0123** [comment]
https://www.wowhead.com/npc=44473/shaggy-black-bear
Can be attacked, but do not react.
![WoWScrnShot_020220_233240](https://user-images.githubusercontent.com/46425985/73691465-b3b0b400-46d2-11ea-8417-6c09d2e9df2d.jpg)

**Comment by Roodypoo0123** [comment]
![WoWScrnShot_020220_223925](https://user-images.githubusercontent.com/46425985/73691829-6aad2f80-46d3-11ea-9cd9-8ab4f2fbfa67.jpg)

**Comment by talosbane00** [comment]
He can attack undeground.
[https://www.wowhead.com/npc=16857/marauding-crust-burster](url)
![Marauding Crust Buster](https://user-images.githubusercontent.com/60328315/73706754-8e836c00-46f9-11ea-8c9e-1ecc641e2c28.jpg)

**Comment by talosbane00** [comment]
No movement at all and no reactions.
[https://www.wowhead.com/npc=46869/marshtide-invader](url)
![Marshtide Invaders](https://user-images.githubusercontent.com/60328315/73706803-bb378380-46f9-11ea-97d6-95d919f65a69.jpg)

**Comment by talosbane00** [comment]
Double Jarroc Torn-Wing and Gomegaz.
[https://www.wowhead.com/quest=25694/protecting-our-rear](url)
https://www.wowhead.com/npc=41164/jarroc-torn-wing
https://www.wowhead.com/npc=41166/gomegaz
![Protecting our rear 2](https://user-images.githubusercontent.com/60328315/73706872-0356a600-46fa-11ea-89f1-c703adfae708.jpg)
![Protecting our rear](https://user-images.githubusercontent.com/60328315/73706877-05b90000-46fa-11ea-8e39-ea25bf7acf74.jpg)

**Comment by talosbane00** [comment]
No movement at all.
[https://www.wowhead.com/npc=46765/stonard-ogre](url)
![Tides of Darkness](https://user-images.githubusercontent.com/60328315/73707265-5d0ba000-46fb-11ea-9eec-8bb07c641fb6.jpg)

**Comment by talosbane00** [comment]
NCPs underground.
[https://www.wowhead.com/npc=16933/razorfang-ravager](url)
[https://www.wowhead.com/npc=19190/fel-handler](url)
[https://www.wowhead.com/npc=16863/deranged-helboar](url)
![Razorfang Ravager](https://user-images.githubusercontent.com/60328315/73765635-178bb900-4775-11ea-9574-521e454aa9cc.jpg)
![Fel Handler](https://user-images.githubusercontent.com/60328315/73765640-19557c80-4775-11ea-930a-2b71bbeede5b.jpg)
![Deranged Helboar](https://user-images.githubusercontent.com/60328315/73765645-1b1f4000-4775-11ea-90fb-17c1e47190eb.jpg)

**Comment by talosbane00** [comment]
Fulgorge is invisible in combat.
[https://www.wowhead.com/npc=18678/fulgorge](url)
![Fulrgorge](https://user-images.githubusercontent.com/60328315/73836313-3fc7f600-480f-11ea-9ed1-c024e5570e00.jpg)

**Comment by talosbane00** [comment]
Floating and walking inside textures. Many of them.
[https://www.wowhead.com/npc=18827/ganarg-sapper](url)
![Gan'arg Sapper](https://user-images.githubusercontent.com/60328315/73836394-70a82b00-480f-11ea-8c26-dae0871f4dff.jpg)
![Gan'arg Sapper 2](https://user-images.githubusercontent.com/60328315/73836413-7bfb5680-480f-11ea-9141-6319d20c42db.jpg)

**Comment by talosbane00** [comment]
Check "Ruins Of Sha'Naar" because Illidari Taskmasters and Dreghood Brute often are walking inside textures and sometimes floating a bit.
[https://www.wowhead.com/npc=17058/illidari-taskmaster](url)
[https://www.wowhead.com/npc=16938/dreghood-brute](url)
![Illidari Taskmaster](https://user-images.githubusercontent.com/60328315/73836525-c086f200-480f-11ea-8c74-be110ddd2532.jpg)
![Dreghood Brute](https://user-images.githubusercontent.com/60328315/73836532-c2e94c00-480f-11ea-88a5-b28420871025.jpg)

**Comment by DannyX1** [comment]
The npcs at Raynewood Retreat, Ashenvale, do not fight each other . They just stand idle 

https://classic.wowhead.com/npc=4054/laughing-sister
https://www.wowhead.com/npc=34366/warsong-vanguard

![image](https://user-images.githubusercontent.com/60583773/73873265-0bb0fd00-4830-11ea-879c-9b68df6ed93f.png)

**Comment by DannyX1** [comment]
The mob Hellscream's Hellion, in Astranaar, is in the wrong area. They do not attack nor can they be attacked. 
![image](https://user-images.githubusercontent.com/60583773/73873973-6860e780-4831-11ea-93d3-67095d4f93bf.png)

https://www.wowhead.com/npc=34163/hellscreams-hellion

**Comment by talosbane00** [comment]
NCPs walking underground.
[https://www.wowhead.com/npc=16836/escaped-dreghood](url)
[https://www.wowhead.com/npc=16954/forge-camp-legionnaire](url)
[https://www.wowhead.com/npc=19192/mistress-of-doom](url)
[https://www.wowhead.com/npc=16946/moarg-forgefiend](url)
[https://www.wowhead.com/npc=19188/raging-colossus](url)
[https://www.wowhead.com/npc=19350/thornfang-venomspitter](url)

**Comment by talosbane00** [comment]
Many of them float on the water, others do not get off the ships. Their ships make irregular movements.
[https://www.wowhead.com/npc=25760/kvaldir-raider](url)
![Kvaldir Boat](https://user-images.githubusercontent.com/60328315/73896538-8c4d1900-4883-11ea-9c0c-d8d6d7185970.jpg)
![Kvaldir Boat 2](https://user-images.githubusercontent.com/60328315/73896540-8e16dc80-4883-11ea-8f74-0b9d7dd6709a.jpg)
![Kvaldir Boat 3](https://user-images.githubusercontent.com/60328315/73896546-8fe0a000-4883-11ea-8709-34d6e74e7b0d.jpg)

**Comment by Roodypoo0123** [comment]
Nmaps issues in Outlands.
https://www.wowhead.com/npc=16906/unyielding-knight
![WoWScrnShot_020620_001328](https://user-images.githubusercontent.com/46425985/73941281-40cf5500-48ed-11ea-997e-e71978721982.jpg)

**Comment by talosbane00** [comment]
[https://www.wowhead.com/npc=29427/captive-vrykul](url)
Movement when attack. Otherwise no movement at all.

**Comment by talosbane00** [comment]
Nmap issues.
[https://www.wowhead.com/npc=40080/unbound-flame-spirit](url)
![immagine](https://user-images.githubusercontent.com/60328315/74062526-bbcc6480-49ee-11ea-8786-6b8e0589bf52.png)

**Comment by talosbane00** [comment]
Seems that he can fly xD
[https://www.wowhead.com/npc=29469/ice-steppe-rhino](url)
![immagine](https://user-images.githubusercontent.com/60328315/74091270-e9c8ac00-4ab5-11ea-904c-5f3e73bd425b.png)

**Comment by talosbane00** [comment]
Nmap issue.
[https://www.wowhead.com/npc=30683/father-gustav](url)
![immagine](https://user-images.githubusercontent.com/60328315/74091313-6491c700-4ab6-11ea-93ff-4022cc97f385.png)

**Comment by talosbane00** [comment]
Double Fayran Elthas.
[https://www.wowhead.com/npc=41861/fayran-elthas](url)
![immagine](https://user-images.githubusercontent.com/60328315/74091354-c5210400-4ab6-11ea-8f94-8dd43c8ce388.png)

**Comment by talosbane00** [comment]
Nmap issue.
[https://www.wowhead.com/npc=41396/fiery-tormentor](url)
![immagine](https://user-images.githubusercontent.com/60328315/74091694-72494b80-4aba-11ea-8c4f-d12dcc3c0533.png)

**Comment by talosbane00** [comment]
Double Archdruid Hamuul Runetotem and impossible interact with him for completing quests. Phase issues?
[https://www.wowhead.com/npc=39858/archdruid-hamuul-runetotem](url)
![immagine](https://user-images.githubusercontent.com/60328315/74091727-ee439380-4aba-11ea-954f-2ff23890c474.png)
![immagine](https://user-images.githubusercontent.com/60328315/74091730-fbf91900-4aba-11ea-9395-9577fa39e9d9.png)

**Comment by talosbane00** [comment]
There are some of them too close to the quest area and it is very difficult to complete objectives.
[https://www.wowhead.com/npc=52300/seething-pyrelord](url)
![immagine](https://user-images.githubusercontent.com/60328315/74091769-8fcae500-4abb-11ea-8313-e6bde4436a82.png)

**Comment by Roodypoo0123** [comment]
NPC does not come back to combat after a fear.
![WoWScrnShot_020620_212111](https://user-images.githubusercontent.com/46425985/74112764-9cc10480-4b9f-11ea-9a83-a74286c1f24e.jpg)

**Comment by Roodypoo0123** [comment]
Fulgore not coming up from the ground until dead
![WoWScrnShot_020620_215607](https://user-images.githubusercontent.com/46425985/74112809-e14ca000-4b9f-11ea-9090-d58c06472a15.jpg)

**Comment by Roodypoo0123** [comment]
https://www.wowhead.com/npc=18581/alliance-field-scout
![WoWScrnShot_020720_211200](https://user-images.githubusercontent.com/46425985/74112895-b3b42680-4ba0-11ea-932c-afe5f340ae7d.jpg)

**Comment by Roodypoo0123** [comment]
1 [Mursh lurker ](https://www.wowhead.com/npc=18136/marsh-lurker) in the cave, not possible to attack, not moving.
![WoWScrnShot_020720_212734](https://user-images.githubusercontent.com/46425985/74112918-e9f1a600-4ba0-11ea-9322-cd5116b8e244.jpg)

**Comment by Roodypoo0123** [comment]
https://www.wowhead.com/npc=19012/sparik
![WoWScrnShot_020820_135849](https://user-images.githubusercontent.com/46425985/74113023-c0854a00-4ba1-11ea-84d3-a4f0750d729c.jpg)

**Comment by Roodypoo0123** [comment]
https://classic.wowhead.com/npc=1275/kyra-boucher

![WoWScrnShot_020820_212302](https://user-images.githubusercontent.com/46425985/74113073-19ed7900-4ba2-11ea-83aa-f53e2fe45687.jpg)

**Comment by Maltien** [comment]
https://www.wowhead.com/npc=34560/una-wolfclaw
![WoWScrnShot_021120_214341](https://user-images.githubusercontent.com/60936187/74277303-935aa800-4d17-11ea-9f45-dcd44dd00ffe.jpg)
