### ISSUE TITLE
[Quest] Zen'kiki and the Cultists

### ISSUE THREAD

**Issue by Sedowr** [revui/Legion_7.3.5-Project-Info#266]
Edit: Apparently Zen'kiki is an npc that will heal the bears for you. Never saw him
https://www.wowhead.com/quest=26955/zenkiki-and-the-cultists
![image](https://user-images.githubusercontent.com/60552532/73615533-530d7280-4611-11ea-9ccf-47e495dd44fe.png)

**Comment by talosbane00** [comment]
Duplicate.
[https://github.com/revui/Legion_7.3.5-Project-Info/issues/134](url)

**Comment by DaniloMaglia** [comment]
The quest works so i think you should close the issue
