### ISSUE TITLE
[Quest] Inoculation

### ISSUE THREAD

**Issue by Beefkek** [revui/Legion_7.3.5-Project-Info#3]
There are two versions of the quest.
Version one: https://www.wowhead.com/quest=9303/inoculation
Version two: https://www.wowhead.com/quest=37444/inoculation

Version one should be available only to Draeneis and no other Alliance or Horde race (this might work I did not check).
Version two should be available to all Alliance races except for Draeneis. Atm you can take both as a Draenei.

**Comment by revui** [comment]
Fixed
