### ISSUE TITLE
WRONG TICKET  - DELETE [Spell] Disengage

### ISSUE THREAD

**Issue by talosbane00** [revui/Legion_7.3.5-Project-Info#31]
The Disengage spell crashes the client. I have tried several times and often client crashes immediately after using the spell. I am not sure about other crashes but this seems confirmed.
[https://www.wowhead.com/spell=781/disengage](url)

**Comment by talosbane00** [comment]
Wrong Ticket. It's not this spell that makes client crahs.

**Comment by revui** [comment]
So its invalid?

**Comment by talosbane00** [comment]
Yes, its invalid. Now we know that the problem is the anti hack and not this spell
