### ISSUE TITLE
[Quest] Unexpected Results

### ISSUE THREAD

**Issue by seeflylegion** [revui/Legion_7.3.5-Project-Info#319]
[wowhead](https://www.wowhead.com/quest=8488/unexpected-results)

No mobs appear to defend her from, [Gharsul](https://wow.gamepedia.com/Gharsul_the_Remorseless) stands there even without beginning quest.

Also quest bugs after you complete it, staying in your questlog and spamming complete infotext at the upper part of screen.

**Comment by revui** [comment]
Fixed (Attackers will appears when you pickup the quest)
