### ISSUE TITLE
[Quest] The Finest Down

### ISSUE THREAD

**Issue by talosbane00** [revui/Legion_7.3.5-Project-Info#320]
There are maybe 3-4 Female Kaliri Hatchling without any Kaliri Feather.
Nothing happen if you click on Kaliri Nest.
[https://www.wowhead.com/item=23588/kaliri-feather](url)
[https://www.wowhead.com/npc=17034/female-kaliri-hatchling](url)
[https://www.wowhead.com/quest=9420/the-finest-down](url)
[https://www.wowhead.com/object=181582/kaliri-nest](url)

**Comment by revui** [comment]
Fixed
