### ISSUE TITLE
[Quest] Dark Garb (27452)

### ISSUE THREAD

**Issue by Roodypoo0123** [revui/Legion_7.3.5-Project-Info#325]
The [quest item](https://www.wowhead.com/item=61280/death-cultist-headwear) is not dropping.
![WoWScrnShot_020420_225748](https://user-images.githubusercontent.com/46425985/73796697-3bb7bc00-47ae-11ea-9660-66e548decdfe.jpg)

**Comment by revui** [comment]
Fixed
