### ISSUE TITLE
[Quest] Natural Remedies

### ISSUE THREAD

**Issue by talosbane00** [revui/Legion_7.3.5-Project-Info#326]
Using item quest spawn many Goliathon.
[https://www.wowhead.com/quest=10351/natural-remedies](url)
[https://www.wowhead.com/item=29478/seed-of-revitalization](url)
[https://it.wowhead.com/npc=19305/goliathon](url)
![Natural Remedies - Goliathon](https://user-images.githubusercontent.com/60328315/73835546-d7c4e000-480d-11ea-940c-47ff4bf8d752.jpg)

**Comment by Roodypoo0123** [comment]
![WoWScrnShot_020620_221006](https://user-images.githubusercontent.com/46425985/74112829-0e994e00-4ba0-11ea-9ee4-d57fbb9e4655.jpg)
