### ISSUE TITLE
[Other Stuff] Dark portal

### ISSUE THREAD

**Issue by talosbane00** [revui/Legion_7.3.5-Project-Info#327]
There is a strange barrier that does not make you cross the dark portal to get out of the Outlands.
![Cant go away from Outland](https://user-images.githubusercontent.com/60328315/73836812-68042480-4810-11ea-8993-723a2a9d9f92.jpg)

**Comment by revui** [comment]
Dark portal have a one way entry since WoD.

**Comment by talosbane00** [comment]
Oh. I'm dumb, sorry xD
