### ISSUE TITLE
[Other Stuff] Floating chests Hellfire Citadel

### ISSUE THREAD

**Issue by talosbane00** [revui/Legion_7.3.5-Project-Info#328]
In Hellfire Citadel there are torches that have strange floating chests on the flames.
![Strange Floating Chets 4](https://user-images.githubusercontent.com/60328315/73837251-638c3b80-4811-11ea-850f-0b3cbf83e980.jpg)
![Strange Floating Chets](https://user-images.githubusercontent.com/60328315/73837257-65ee9580-4811-11ea-8876-8015a91e6691.jpg)
![Strange Floating Chets 2](https://user-images.githubusercontent.com/60328315/73837276-68e98600-4811-11ea-84a4-871240baac79.jpg)
![Strange Floating Chets 3](https://user-images.githubusercontent.com/60328315/73837287-6c7d0d00-4811-11ea-8c32-0e849fb3fda3.jpg)

**Comment by revui** [comment]
Fixed
