### ISSUE TITLE
[NPC] Gnome starting zone - Incorrect ambient fight

### ISSUE THREAD

**Issue by Roodypoo0123** [revui/Legion_7.3.5-Project-Info#34]
The starting area in the gnome starting zone has incorrect ambiance fight.
The [NPC](https://www.wowhead.com/npc=46391/crazed-leper-gnome) are aggressive toward the player but are not always aggro-ed in the ambiance fight with the [friendlies](https://www.wowhead.com/npc=46449/s-a-f-e-operative) and when they do they fly all over the place because of a charge-like spell.

**Comment by Roodypoo0123** [comment]
![WoWScrnShot_012720_150346](https://user-images.githubusercontent.com/46425985/73180777-49b66e80-4116-11ea-8ff7-42a1b1dc3f1a.jpg)

**Comment by Roodypoo0123** [comment]
The push backs also cause other NPCs to get aggro-ed in fight like the quest giver : [Carvo](https://www.wowhead.com/npc=47250/carvo-blastbolt)

![WoWScrnShot_012720_151155](https://user-images.githubusercontent.com/46425985/73181439-80d94f80-4117-11ea-8072-5c6d41bef325.jpg)

**Comment by revui** [comment]
Fixed
