### ISSUE TITLE
[NPC] Wounded Infantry

### ISSUE THREAD

**Issue by Roodypoo0123** [revui/Legion_7.3.5-Project-Info#37]
The [NPC](https://www.wowhead.com/npc=42501/wounded-infantry) is spawned with a gobelin for some reason

![WoWScrnShot_012720_152217](https://user-images.githubusercontent.com/46425985/73182635-b2ebb100-4119-11ea-8c7c-fa09e9f2e508.jpg)

**Comment by Roodypoo0123** [comment]
Looks like its more related to the item tied to the gobelin than the NPC.

![WoWScrnShot_012720_153306](https://user-images.githubusercontent.com/46425985/73183020-62c11e80-411a-11ea-8afd-325a8a0e2f1b.jpg)

**Comment by revui** [comment]
Fixed
