### ISSUE TITLE
[Quest] Scrounging for parts (26222)

### ISSUE THREAD

**Issue by Roodypoo0123** [revui/Legion_7.3.5-Project-Info#38]
The "medic bed" under the [NPC](https://www.wowhead.com/npc=42501/wounded-infantry) becomes collectible when accepting the quest when it should only be a cosmetic item.

![WoWScrnShot_012720_152217](https://user-images.githubusercontent.com/46425985/73182887-2988ae80-411a-11ea-892a-d4a911b15566.jpg)

**Comment by revui** [comment]
Fixed
