### ISSUE TITLE
[NPC] Gomegaz

### ISSUE THREAD

**Issue by Roodypoo0123** [revui/Legion_7.3.5-Project-Info#382]
Multiple spawns for the [hell hound](https://www.wowhead.com/npc=41166/gomegaz) in the blasted lands.

![WoWScrnShot_020520_225239](https://user-images.githubusercontent.com/46425985/73941009-c1da1c80-48ec-11ea-806b-c0dcddb79a2e.jpg)

**Comment by talosbane00** [comment]
Already reported.

**Comment by Roodypoo0123** [comment]
erf... Search does not parse the megathread... Closing.
