### ISSUE TITLE
[Rare Mob] Muad Loot Table wrong

### ISSUE THREAD

**Issue by toolshmool** [revui/Legion_7.3.5-Project-Info#4]
I got a level 80 grey belt out of the Rare Mob Muad

https://www.wowhead.com/npc=1910/muad
![WoWScrnShot_012620_215207](https://user-images.githubusercontent.com/60327939/73141692-314b4300-4087-11ea-83b4-708687b4150c.jpg)

**Comment by revui** [comment]
Fixed. Will implemented with the next update.
