### ISSUE TITLE
[Quest] Down with Crushcog! (26364)

### ISSUE THREAD

**Issue by Roodypoo0123** [revui/Legion_7.3.5-Project-Info#41]
Talking to High Tinker Mekkatorque properly validate the quest task but does not trigger the assault on Crushcog and renders the quest unable to complete.

![WoWScrnShot_012720_161026](https://user-images.githubusercontent.com/46425985/73186572-41633100-4120-11ea-8420-dc16ee7d602d.jpg)

**Comment by revui** [comment]
Fixed - but the encounter is still missing (WIP)
