### ISSUE TITLE
[Quest] HELP!

### ISSUE THREAD

**Issue by Roodypoo0123** [revui/Legion_7.3.5-Project-Info#467]
Corki refuse to be free, even after opening the cage.
https://www.wowhead.com/quest=9923/help
![WoWScrnShot_020820_030700](https://user-images.githubusercontent.com/46425985/74112956-481e8900-4ba1-11ea-97a8-c5c286e4d5bb.jpg)

**Comment by talosbane00** [comment]
Already reported.
