### ISSUE TITLE
[Quest] Windroc Mastery

### ISSUE THREAD

**Issue by Roodypoo0123** [revui/Legion_7.3.5-Project-Info#469]
Gutripper is not lootable, should have at least the quest item, 100%.

https://www.wowhead.com/quest=9856/windroc-mastery
![WoWScrnShot_020820_032555](https://user-images.githubusercontent.com/46425985/74113007-aba8b680-4ba1-11ea-9f83-581cafb1ad78.jpg)

**Comment by Kexxi** [comment]
I got it from first kill sometimes the qitem not 100%
