### ISSUE TITLE
[Quest] The Holy Water of Clarity 

### ISSUE THREAD

**Issue by Zube18** [revui/Legion_7.3.5-Project-Info#471]
https://www.wowhead.com/quest=26433/the-holy-water-of-clarity

There is no loot in the well. (Empty Loot when looting)

**Comment by Kexxi** [comment]
I reported already

**Comment by Zube18** [comment]
![image](https://user-images.githubusercontent.com/54475753/74141386-1cc68900-4bf7-11ea-920a-d3f9dae6b241.png)
couldnt find it

**Comment by Kexxi** [comment]
https://github.com/revui/Legion_7.3.5-Project-Info/issues/193#issue-558553142

**Comment by Zube18** [comment]
My bad. Sorry.
