### ISSUE TITLE
[NPC] Pandaren starting zone - Incorrect ambient fight

### ISSUE THREAD

**Issue by Roodypoo0123** [revui/Legion_7.3.5-Project-Info#49]
The monkeys are not properly triggered in the ambient fight, resulting in a massive chimp pull when the player arrives.

![WoWScrnShot_012720_201243](https://user-images.githubusercontent.com/46425985/73205568-85b2f900-4141-11ea-8c1b-d202946fced7.jpg)

**Comment by revui** [comment]
Fixed
