### ISSUE TITLE
[Quest] A Scarlet Letter

### ISSUE THREAD

**Issue by toolshmool** [revui/Legion_7.3.5-Project-Info#5]
The "Scarlet Warrior" in Tirisfal Glades should drop the Item that starts the quest "A Scarlet Letter". I killed 10+ enemies and got no drop. On retail (during legion) you had to kill 2-3 to get it.

https://www.wowhead.com/npc=1535/scarlet-warrior

![WoWScrnShot_012620_220626](https://user-images.githubusercontent.com/60327939/73141794-7328b900-4088-11ea-956b-a48a89e70e74.jpg)

**Comment by revui** [comment]
Fixed. Will implemented with the next update.
