### ISSUE TITLE
[NPC] Incorrect Tushui Monk spawns

### ISSUE THREAD

**Issue by Roodypoo0123** [revui/Legion_7.3.5-Project-Info#50]
In the starting area of the Pandarens, the monks balancing over the bamboos are too many and flying stationary:

![WoWScrnShot_012720_204108](https://user-images.githubusercontent.com/46425985/73207712-79c93600-4145-11ea-833a-a632b3a16c32.jpg)

**Comment by revui** [comment]
Fixed
