### ISSUE TITLE
[NPC] Double spawns in Mulgore 

### ISSUE THREAD

**Issue by Roodypoo0123** [revui/Legion_7.3.5-Project-Info#52]
Quite the population in Mulgore areas as all entities spawns twice

![WoWScrnShot_012720_215234](https://user-images.githubusercontent.com/46425985/73212882-6fac3500-414f-11ea-93ad-2f78411a3cb1.jpg)

![WoWScrnShot_012720_215338](https://user-images.githubusercontent.com/46425985/73212909-7dfa5100-414f-11ea-9ad9-e1bbbcfa961c.jpg)

**Comment by revui** [comment]
Fixed
