### ISSUE TITLE
[Rogue] Crimson Vial

### ISSUE THREAD

**Issue by Illustratex** [revui/Legion_7.3.5-Project-Info#522]
[Crimson Vial](https://www.wowhead.com/spell=185311/crimson-vial#changelog) tooltip shows only 20% of your maximum hp, should be 30%
[Proof](https://gyazo.com/02a0382bc130f67d1941eaad1dfaf91f)

**Comment by revui** [comment]
30% applies when you use it, just the tooltip bugged?

**Comment by Illustratex** [comment]
yes its just the tooltip is bugged, was showing 30% before the recent update

**Comment by revui** [comment]
Tried after a chache deletion? And on which character you noticed it? Prpper leveled one, or boosted?

**Comment by Illustratex** [comment]
leveling character shows 30% boosted character shows 20%

**Comment by revui** [comment]
In this case the issue is appears with the boosted characters. I will look into this for the future, so I wont close this report (however the boost will only an Alpha feature)
