### ISSUE TITLE
[Quest] A Deadly Vine

### ISSUE THREAD

**Issue by talosbane00** [revui/Legion_7.3.5-Project-Info#53]
Wrong Area Quest
[https://www.wowhead.com/quest=26707/a-deadly-vine](url)
![A Deadly Vine](https://user-images.githubusercontent.com/60328315/73224543-1a315180-416a-11ea-8465-9832d5973946.jpg)
![A Deadly Vine 2](https://user-images.githubusercontent.com/60328315/73224547-1ef60580-416a-11ea-80bf-53b587acc85a.jpg)

**Comment by revui** [comment]
Fixed
