### ISSUE TITLE
Quest - A Curse We Cannot Lift

### ISSUE THREAD

**Issue by JadedNate** [revui/Legion_7.3.5-Project-Info#532]
The NPC, Lurking Worgen, required for the quest is stuck in the barn wall and cannot be interacted with.

![WoWScrnShot_021720_191020](https://user-images.githubusercontent.com/57082188/74693289-26349000-51b9-11ea-943f-1e42e068a3f9.jpg)

https://www.wowhead.com/quest=26720/a-curse-we-cannot-lift

**Comment by talosbane00** [comment]
Already reported.
