### ISSUE TITLE
[Quest] Classy Glass

### ISSUE THREAD

**Issue by talosbane00** [revui/Legion_7.3.5-Project-Info#56]
Wrong Area Quest
[https://www.wowhead.com/quest=26685/classy-glass](url)
![Classy Glass](https://user-images.githubusercontent.com/60328315/73224684-8dd35e80-416a-11ea-8ebb-edf970576f4c.jpg)
![Classy Glass 2](https://user-images.githubusercontent.com/60328315/73224686-8f9d2200-416a-11ea-8218-25c7157ff5cb.jpg)

**Comment by revui** [comment]
Fixed
