### ISSUE TITLE
[Quest] Gather Rot Blossoms

### ISSUE THREAD

**Issue by talosbane00** [revui/Legion_7.3.5-Project-Info#60]
Wrong Area Quest
[https://www.wowhead.com/quest=26661/gather-rot-blossoms](url)
![Gather Rot Blossoms](https://user-images.githubusercontent.com/60328315/73224892-426d8000-416b-11ea-9981-a20e3ae9c523.jpg)
![Gather Rot Blossoms 2](https://user-images.githubusercontent.com/60328315/73224893-44374380-416b-11ea-8757-ae1643999ff2.jpg)

**Comment by revui** [comment]
Fixed
