### ISSUE TITLE
[Quest] Sacred to the Bloodscalp

### ISSUE THREAD

**Issue by talosbane00** [revui/Legion_7.3.5-Project-Info#68]
Wrong Area Quest
[https://www.wowhead.com/quest=26743/sacred-to-the-bloodscalp](url)
![Sacred to the Bloodscalp](https://user-images.githubusercontent.com/60328315/73225260-58c80b80-416c-11ea-8efe-7c19aa3a9758.jpg)

**Comment by revui** [comment]
Fixed
