### ISSUE TITLE
[Quest] Variety is the Spice of Death

### ISSUE THREAD

**Issue by toolshmool** [revui/Legion_7.3.5-Project-Info#7]
Xavren's Thorn isn't spawning. No spawns at all.
![WoWScrnShot_012620_221817](https://user-images.githubusercontent.com/60327939/73141972-e41ca080-4089-11ea-9f92-fb7b0e6cfbc3.jpg)

**Comment by revui** [comment]
Fixed. Will implemented with the next update.

**Comment by revui** [comment]
IMPORTANT UPDATE:
Some issues are caused by the Xavren's Thorn object. As a temporary solution, Its removed completly from the game. You need to drop your quest, and pick it up again. When you collect your "Marrowpetal" quest items, you will get Xavren's Thorn aswell.
