### ISSUE TITLE
[Quest] Stopping Kurzen's Legacy

### ISSUE THREAD

**Issue by talosbane00** [revui/Legion_7.3.5-Project-Info#70]
Wrong Area Quest
[https://www.wowhead.com/quest=26737/stopping-kurzens-legacy](url)
![Stopping Kurzen's Legacy](https://user-images.githubusercontent.com/60328315/73225332-975dc600-416c-11ea-84f6-cd8459d343da.jpg)

**Comment by revui** [comment]
Fixed
