### ISSUE TITLE
[Quest] The Fate of Morbent Fel

### ISSUE THREAD

**Issue by talosbane00** [revui/Legion_7.3.5-Project-Info#72]
Wrong Area Quest
[https://www.wowhead.com/quest=26723/the-fate-of-morbent-fel](url)
![The Fate of Morbent Fel](https://user-images.githubusercontent.com/60328315/73225387-cd02af00-416c-11ea-9235-7cf1178a8acd.jpg)

**Comment by revui** [comment]
Fixed
