### ISSUE TITLE
[Quest] The Rotting Orchard

### ISSUE THREAD

**Issue by talosbane00** [revui/Legion_7.3.5-Project-Info#74]
Wrong Area Quest
[https://www.wowhead.com/quest=26689/the-rotting-orchard](url)
![The Rotting Orchard](https://user-images.githubusercontent.com/60328315/73225460-0804e280-416d-11ea-9a19-a9ad9df1b4c0.jpg)
![The Rotting Orchard 2](https://user-images.githubusercontent.com/60328315/73225461-09360f80-416d-11ea-9dc2-104a195c0b98.jpg)

**Comment by revui** [comment]
Fixed
