### ISSUE TITLE
[Quest] The Yorgen Worgen

### ISSUE THREAD

**Issue by talosbane00** [revui/Legion_7.3.5-Project-Info#76]
Wrong Area Quest
[https://www.wowhead.com/quest=26717/the-yorgen-worgen](url)
![The Yorgen Worgen](https://user-images.githubusercontent.com/60328315/73225508-45697000-416d-11ea-91e3-98fb6fd2e88a.jpg)

**Comment by revui** [comment]
Minimap shows the right place, but the map not. Will fixed soon
