### ISSUE TITLE
[Quest] Vulgar Vul'Gol

### ISSUE THREAD

**Issue by talosbane00** [revui/Legion_7.3.5-Project-Info#78]
Wrong Area Quest
[https://www.wowhead.com/quest=25235/vulgar-vulgol](url)
![Vulgar Vul'Gol](https://user-images.githubusercontent.com/60328315/73225582-83ff2a80-416d-11ea-8ecc-f4db9644ac53.jpg)

**Comment by revui** [comment]
Fixed
