### ISSUE TITLE
[Spell][Warrior] Victory Rush

### ISSUE THREAD

**Issue by Beefkek** [revui/Legion_7.3.5-Project-Info#8]
If you have the Victory Rush buff (Victorious, ID 32216) and you kill a mob using the spell Victory Rush you will not get a new Victorious buff.

How it should work: As long as you landed the killing blow, no matter what skill you used, you should get the buff or refresh its duration if you already had it.

**Comment by revui** [comment]
Can not repruduce this issues. Need more tests

**Comment by Beefkek** [comment]
I can reproduce it 100% of the time.

Step by step guide!
1. Pull 3 mobs
2. Kill only one of them. You get the buff and you can use victory rush now (don't use it yet!)
3. Get the second mob low enough to be able to kill it with victory rush. The buff still needs to be active before you kill it.
4. Kill the second mob with victory rush.
5. Notice how you did not get a new buff and how you are not able to use victory rush on the third mob.

Here is a video, notice how I get the buff after killing first mob but not after killing the second mob.
https://vimeo.com/387318053

**Comment by Beefkek** [comment]
> Can not repruduce this issues. Need more tests

^

**Comment by revui** [comment]
I don't know if its needed to proc on when the target is killed with <Victory Rush>.
Need verification (official post or retail) for it.

**Comment by Beefkek** [comment]
http://prntscr.com/qvyumo
^ all the changes that ever happened to the spell.
The only requirement is that you are the one who deals the killing blow and that the enemy you kill yields exp or honor.

**Comment by revui** [comment]
I've seen that, and checked at wowhead aswell, but for the VR as KB not mentioned anywhere. Need to install retail client to confirm this

**Comment by Beefkek** [comment]
Neither is any other spell xD but ok do ur thing.
