### ISSUE TITLE
[Npc] Commander Althea Ebonlocke

### ISSUE THREAD

**Issue by talosbane00** [revui/Legion_7.3.5-Project-Info#80]
Unfriendly and Targetable
[https://it.classic.wowhead.com/npc=264/commander-althea-ebonlocke](url)
![Althea Ebonlocke](https://user-images.githubusercontent.com/60328315/73225688-d2acc480-416d-11ea-8473-5039c5f00d90.jpg)

**Comment by revui** [comment]
Fixed
