### ISSUE TITLE
[Npc] Gavin Gnarltree

### ISSUE THREAD

**Issue by talosbane00** [revui/Legion_7.3.5-Project-Info#82]
Walk on the roof of the building
[https://it.classic.wowhead.com/npc=225/gavin-gnarltree](url)
![Gavin Gnarltree](https://user-images.githubusercontent.com/60328315/73225797-27e8d600-416e-11ea-8c79-40865c2a92e0.jpg)

**Comment by revui** [comment]
Fixed
