### ISSUE TITLE
[Npc] Kurzen Medicine Man

### ISSUE THREAD

**Issue by talosbane00** [revui/Legion_7.3.5-Project-Info#83]
Some of them walk underground (those who are swordless)
[https://it.classic.wowhead.com/npc=940/kurzen-medicine-man](url)
![Kurzen Medicine Man](https://user-images.githubusercontent.com/60328315/73225868-6aaaae00-416e-11ea-8d45-088cba25dd57.jpg)

**Comment by revui** [comment]
Fixed
