### ISSUE TITLE
[Npc] Stranglethorn Tiger

### ISSUE THREAD

**Issue by talosbane00** [revui/Legion_7.3.5-Project-Info#87]
Some of these tigers walk underground or through trees
[https://it.classic.wowhead.com/npc=682/stranglethorn-tiger](url)
![Stranglethorn Tiger](https://user-images.githubusercontent.com/60328315/73226224-94b0a000-416f-11ea-96f8-d9d813439afc.jpg)

**Comment by revui** [comment]
Fixed
