### ISSUE TITLE
[Other stuff] Strange untargetable Skull

### ISSUE THREAD

**Issue by talosbane00** [revui/Legion_7.3.5-Project-Info#89]
In the Duskwood Blacksmith building there is a strange skull
![Strange Skull](https://user-images.githubusercontent.com/60328315/73226384-23252180-4170-11ea-9746-5974c2f11150.jpg)

**Comment by revui** [comment]
Its a reference for the Rogues Kingslayer Artifact quest. - Fixed (added the missing Altar)
