### ISSUE TITLE
Client Crash Error WOW51900319

### ISSUE THREAD

**Issue by talosbane00** [revui/Legion_7.3.5-Project-Info#9]
I can't understand why my client crash many many times with Error WOW51900319.
I downloaded the full client from wow-mortal. 
I tried to delete the cache folder and run wow-64.exe with administrator privileges but nothing has changed.
This problem occurs randomly. I thought it happened while I was using a spell but I was wrong.
It is very frustrating.

**Comment by Roodypoo0123** [comment]
Same error, 99.9% sure it's linked to the warden.
