### ISSUE TITLE
[Quest] Sharing the land (745)

### ISSUE THREAD

**Issue by Roodypoo0123** [revui/Legion_7.3.5-Project-Info#90]
Return location for this [quest ](https://classic.wowhead.com/quest=745/sharing-the-land) is not at the right place on the map.

![WoWScrnShot_012820_103311](https://user-images.githubusercontent.com/46425985/73251712-c189a500-41b9-11ea-841a-51d8382ac027.jpg)

**Comment by revui** [comment]
Fixed
