### ISSUE TITLE
Disturbance in the Matrix

### ISSUE THREAD

**Issue by Kexxi** [revui/Legion_7.3.5-Project-Info#92]
This npc is chopping the Dirt 

![73272663-083fc500-41e3-11ea-9fa0-883e5b6b3d4f](https://user-images.githubusercontent.com/60041403/73272721-23aad000-41e3-11ea-944d-802b1cab8f8d.png)

**Comment by Kexxi** [comment]
https://www.youtube.com/watch?v=TPE7ALB7IUU

**Comment by revui** [comment]
Fixed
