### ISSUE TITLE
[Npc] Digsite Zombie

### ISSUE THREAD

**Issue by talosbane00** [revui/Legion_7.3.5-Project-Info#94]
There are many Digsite Zombie (level 85) in this area.
They are unfriendly and they don't attack you (even if you walk close to them) but they attack you if you attack them.
[https://www.wowhead.com/npc=52604/digsite-zombie](url)
![Digsite Zombie](https://user-images.githubusercontent.com/60328315/73385051-b3787900-42cc-11ea-977e-18cb61eb2d1a.jpg)
![Digsite Zombie 2](https://user-images.githubusercontent.com/60328315/73385060-b7a49680-42cc-11ea-91f6-e0ed14647e88.jpg)

**Comment by Roodypoo0123** [comment]
Confirmed.
