### ISSUE TITLE
[Quest] The Altar of Naias

### ISSUE THREAD

**Issue by talosbane00** [revui/Legion_7.3.5-Project-Info#97]
There are too many Naias and in this way is impossible to complete this quest.
[https://www.wowhead.com/quest=26731/the-altar-of-naias](url)
[https://it.wowhead.com/npc=17207/naias](url)
![Naias](https://user-images.githubusercontent.com/60328315/73388684-fa696d00-42d2-11ea-9ea5-d872b6db732b.jpg)

**Comment by revui** [comment]
Fixed
